[package]
name = "zsh-histdb-skim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skim = "*"
rusqlite = "*"
tuikit = "*"
chrono = "*"
enum-map = "*"
log = "0.4"
textwrap = "0.15"
